name: change_app_name
description: Change App Package Name & Launcher Name with single command.
version: 1.0.0
maintainer: Gilbert Mena (@hibrid)
homepage: https://github.com/motivq/change_app_name

environment:
  sdk: '>=2.12.0 <4.0.0'
dependencies:
  xml: ^6.5.0
dev_dependencies:
  test: ^1.25.14
  mockito: ^5.4.5
